# Generated by Django 2.0 on 2018-09-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_type',
            old_name='device_type_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='producter',
            old_name='producter_text',
            new_name='text',
        ),
    ]
