# Generated by Django 2.0 on 2018-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20180913_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internet_Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', unique=True, verbose_name='公网IP')),
            ],
            options={
                'verbose_name_plural': '外网IP',
            },
        ),
    ]
