# Generated by Django 2.0 on 2018-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_internet_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intranet_Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField(verbose_name='网段')),
            ],
            options={
                'verbose_name_plural': '网段',
            },
        ),
    ]
