# Generated by Django 2.0 on 2018-09-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_info',
            name='env',
            field=models.CharField(choices=[('开发环境', '开发环境'), ('测试环境', '测试环境'), ('生产环境', '生产环境')], default='开发环境', max_length=400, verbose_name='所属环境'),
        ),
        migrations.AlterField(
            model_name='pc_info',
            name='remark',
            field=models.TextField(verbose_name='备注/维修更改记录'),
        ),
        migrations.AlterField(
            model_name='server_info',
            name='remark',
            field=models.TextField(verbose_name='备注/涉及项目'),
        ),
    ]
