# Generated by Django 2.0 on 2018-09-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_info', '0002_auto_20180911_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc_info',
            options={'verbose_name_plural': '电脑资产详情'},
        ),
    ]
