# Generated by Django 2.0 on 2018-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_info', '0008_nat_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nat_info',
            options={'verbose_name': 'NAT映射', 'verbose_name_plural': 'NAT映射'},
        ),
        migrations.AlterField(
            model_name='nat_info',
            name='in_port',
            field=models.CharField(max_length=50, verbose_name='内网端口'),
        ),
        migrations.AlterField(
            model_name='nat_info',
            name='out_port',
            field=models.CharField(max_length=50, unique=True, verbose_name='外网端口'),
        ),
    ]
